### PR TITLE
Fix invalid state when signing up

### LINKED ISSUE #1967: iOS app crashes when new signup adds project
Steps to repro:
- download Toggl app
- sign up for new accnt in iOS app
- start a timer, go to assign a project
- tap "+" to add new project, app crashes

removing and reinstalling the app fixes it

### PR DESCRIPTION
**Pull request by willsb**
Closes #1967

### CODE REVIEW

File: Phoebe/Net/TogglRestClient.cs [hunk 1]
```diff
@@ -839,6 +839,13 @@ public Task DeleteProjectUser(string authToken, ProjectUserJson jsonObject)
 
             var user = await CreateObject(string.Empty, url, jsonObject).ConfigureAwait(false);
 
+            //HACK Backend sometimes creates the account, but fails to return a valid ApiToken.
+            // In such cases, since the account has been succesfully created, we login the user using its credentials
+            if (user != null && string.IsNullOrEmpty(user.ApiToken))
```
Comment (amulware) [inline Phoebe/Net/TogglRestClient.cs]: Please log this as a warning so that we can keep an eye on it on insights.
