### PR TITLE
Small fixes and improvements

### LINKED ISSUE #1094: Remove "Alpha state" from app settings
This is confusing to many of our users (including me). Thank you.

### PR DESCRIPTION
**Pull request by taavirehemagi**
Closes #1094, #1074, #952, #1087, #1095, #1088, #1097

### CODE REVIEW

**Comment by taavirehemagi** [comment]
Default state of settings for new user in this PR.
screen shot 2015-12-14 at 15 55 39

File: Joey/UI/Activities/EditTimeEntryActivity.cs [hunk 1]
```diff
@@ -59,6 +62,12 @@ protected override void OnCreateActivity (Bundle state)
                     .Commit ();
                 }
             }
+
+            if (openProjects) {
```
Comment (monday8am) [inline Joey/UI/Activities/EditTimeEntryActivity.cs]: you can check Settings directly, you don't need to pass from the previous activity (IMO)
`var settingsStore = ServiceContainer.Resolve<SettingsStore> ();`

File: Joey/UI/Fragments/LogTimeEntriesListFragment.cs [hunk 2]
```diff
@@ -109,6 +110,18 @@ public override View OnCreateView (LayoutInflater inflater, ViewGroup container,
             if (ViewModel.HasMore) {
                 OBMExperimentManager.Send (OBMExperimentManager.HomeEmptyState, "startButton", "click");
             }
+
+            if (ViewModel.IsTimeEntryRunning) {
+
+                var intent = new Intent (Activity, typeof (EditTimeEntryActivity));
+                IList<string> guids = ((TimeEntryHolder)logAdapter.GetEntry (1)).TimeEntryGuids;
+                intent.PutStringArrayListExtra (EditTimeEntryActivity.ExtraGroupedTimeEntriesGuids, guids);
```
Comment (monday8am) [inline Joey/UI/Fragments/LogTimeEntriesListFragment.cs]: in this method you have this line:
`await ViewModel.StartStopTimeEntry ();`

you could replace it by:
`var timeEntry = await ViewModel.StartStopTimeEntry ();`

you can use the timeEntry.Id to pass it to the edit class (more reliable than the `logAdapter`). And you always *start* single time entries, not groups, group checking maybe is not needed.

File: Joey/UI/Activities/EditTimeEntryActivity.cs [hunk 3]
```diff
@@ -59,6 +62,12 @@ protected override void OnCreateActivity (Bundle state)
...
+                var intent = new Intent (this, typeof (ProjectListActivity));
+                intent.PutExtra (BaseActivity.IntentWorkspaceIdArgument,  guids[0]);
+                StartActivityForResult (intent, 0);
+            }
         }
```
Comment (monday8am) [inline Joey/UI/Activities/EditTimeEntryActivity.cs]: This solution fails because the data is saved in the intent and it tries to open the ProjectListActivity again and again. In a future we'll use fragments :) .. for the moment, we should use a *one-time* flag or something similar.

**Comment by taavirehemagi** [comment]
I think it's better now. What  do you think?

**Comment by monday8am** [comment]
I'll take a look right now to merge it. Just rebase it with master (a terrible task :dancer:) ..

**Comment by taavirehemagi** [comment]
The change works good for me! :+1: Can we merge? @alfonsogarciacaro @monday8am
